# Generated by Django 3.2.2 on 2021-10-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0002_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localization',
            old_name='adress',
            new_name='address',
        ),
    ]
