# Generated by Django 3.2.2 on 2021-10-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0003_rename_adress_localization_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zapisy.player'),
        ),
    ]
