# Generated by Django 3.2.2 on 2021-10-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0004_alter_entry_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapisy.player'),
        ),
    ]
