# Generated by Django 3.2.2 on 2022-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0004_auto_20220102_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='event',
            name='include_in_rank',
            field=models.BooleanField(default=True),
        ),
    ]
