# Generated by Django 3.2.2 on 2021-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0005_alter_entry_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='signed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
