# Generated by Django 3.2.2 on 2021-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0006_entry_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='signed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
