# Generated by Django 3.2.2 on 2021-11-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0007_alter_entry_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='signed',
            new_name='created_at',
        ),
    ]
