# Generated by Django 3.2.2 on 2021-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0008_rename_signed_entry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reserve',
            field=models.BooleanField(default=False),
        ),
    ]
