# Generated by Django 3.2.2 on 2021-11-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0009_entry_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_entries', to='zapisy.event'),
        ),
    ]
