# Generated by Django 3.2.2 on 2021-11-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0010_alter_entry_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapisy.event'),
        ),
    ]
