# Generated by Django 3.2.2 on 2021-11-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0011_alter_entry_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
